# Introducción a Numpy, Pandas y Matplotlib

## Dataset: Ventas de videojuegos

- Numpy: operacion númericas y álgebra vectorial

- Pandas: Manipulación y anális de datos tabulares

- Matplotlib Visusalización de datos

Uso de `!` y `%` nos sirve para ejcutar comandos desde la terminal

`!` Cuando ejecutamos los comandos no valida entornos
`%` Valida entornos en los comandos

In [2]:
%pip install pandas
%pip install numpy
%pip install matplotlib

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

# Numpy

In [7]:
ventas_na = np.array([41.49, 29.08, 15.85, 15.75, 11.27]) # Vetnas por milloes
ventas_eu = np.array([29.02,  3.58, 12.88, 11.01,  8.89])

print("Arreglo: ", ventas_na)
print("Tipo de dato:", ventas_na.dtype)
print("Dimensiones:", ventas_na.ndim)
print("Forma", ventas_na.shape)

Arreglo:  [41.49 29.08 15.85 15.75 11.27]
Tipo de dato: float64
Dimensiones: 1
Forma (5,)

In [10]:
# Operaciones

ventas_total = ventas_na + ventas_eu
print("Ventas totales", ventas_total)

ventas_miles = ventas_na * 1000000
print("Ventas valor real", ventas_miles)

Ventas totales [70.51 32.66 28.73 26.76 20.16]
Ventas valor real [41490000. 29080000. 15850000. 15750000. 11270000.]

In [11]:
# Estadistica

print("Media", np.mean(ventas_na))
print("Mediana", np.median(ventas_na))
print("Deviación estandar:", np.std(ventas_na))
print("Minimo", np.min(ventas_na))
print("Maximo", np.max(ventas_na))

Media 22.687999999999995
Mediana 15.85
Deviación estandar: 11.132274520510173
Minimo 11.27
Maximo 41.49

In [12]:
# Subconjuntos del arreglo

print("Primer elemento:", ventas_na[0])
print("Úlitmos 3:", ventas_na[-3:])

# Filtros - Mascaras

grandes = ventas_na[ventas_na > 20]
print("Venstas mayores a 20 M:", grandes)

Primer elemento: 41.49
Úlitmos 3: [15.85 15.75 11.27]
Venstas mayores a 20 M: [41.49 29.08]

In [14]:
# Arreglos 2D

matriz_ventas = np.column_stack([ventas_na, ventas_eu])
print("Forma:", matriz_ventas.shape)
print(matriz_ventas)

# Operaciones sobre ejes
print("Media por region", np.mean(matriz_ventas, axis=0))
print("Total por juegos", np.sum(matriz_ventas, axis=1))

Forma: (5, 2)
[[41.49 29.02]
 [29.08  3.58]
 [15.85 12.88]
 [15.75 11.01]
 [11.27  8.89]]
Media por region [22.688 13.076]
Total por juegos [70.51 32.66 28.73 26.76 20.16]

In [16]:
# Generación de nuemeros

rng = np.random.default_rng(seed=42)
muestra_aleatoria = rng.normal(loc=10, scale=5, size=1000)
print("Media:", muestra_aleatoria.mean())
print("Desviacion estandar", muestra_aleatoria.std())
print("forma", muestra_aleatoria.shape)

Media: 9.855542245020267
Desviacion estandar 4.94361177698254
forma (1000,)

# Pandas

In [17]:
df = pd.read_csv("vgsales.csv")
df.shape

(16598, 11)

In [18]:
# Limpieza

print("Valores por columna")
print(df.isnull().sum())

Valores por columna
Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [19]:
df_limpio = df.dropna(subset=["Year", "Publisher"])
print("Filas originales:", len(df))
print("Limpio:", len(df_limpio))

Filas originales: 16598
Limpio: 16291

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  object
 5   Publisher     16540 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

In [21]:
df_limpio = df_limpio.copy()
df_limpio["Year"] = df_limpio["Year"].astype(int)
print(df_limpio.info())

<class 'pandas.core.frame.DataFrame'>
Index: 16291 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16291 non-null  int64
 1   Name          16291 non-null  object
 2   Platform      16291 non-null  object
 3   Year          16291 non-null  int64
 4   Genre         16291 non-null  object
 5   Publisher     16291 non-null  object
 6   NA_Sales      16291 non-null  float64
 7   EU_Sales      16291 non-null  float64
 8   JP_Sales      16291 non-null  float64
 9   Other_Sales   16291 non-null  float64
 10  Global_Sales  16291 non-null  float64
dtypes: float64(5), int64(2), object(4)
memory usage: 1.5+ MB
None

In [23]:
# Duplicados

n_duplicados = df_limpio.duplicated().sum()
print("Duplicados", n_duplicados)
df_limpio = df_limpio.drop_duplicates()

Duplicados 0

In [25]:
# Renombrado de columas

df_limpio = df_limpio.rename(columns={
    "NA_Sales"     : "ventas_na",
    "EU_Sales"     : "ventas_eu",
    "JP_Sales"     : "ventas_jp",
    "Other_Sales"  : "ventas_otros",
    "Global_Sales" : "ventas_global",
})

In [28]:
p99 = df_limpio["ventas_global"].quantile(0.99)
outliners = df_limpio[df_limpio["ventas_global"] > p99]

print("Percentil 99:", p99)
print("Oulilers:", len(outliners))

Percentil 99: 5.472000000000007
Oulilers: 163

In [30]:
# Columnas derivas

df_limpio["ventas_occidente"] = df_limpio["ventas_na"] + df_limpio['ventas_eu']
df_limpio["prop_na"] = df_limpio["ventas_na"] / df_limpio["ventas_global"]
df_limpio[["Name", "ventas_na", "ventas_eu", "ventas_occidente", "prop_na"]].sample(5)

,Name,ventas_na,ventas_eu,ventas_occidente,prop_na
2273,Homefront,0.32,0.40,0.72,0.351648
12539,Toriko: Gourmet Battle!,0.00,0.00,0.00,0.000000
12058,Dynasty Warriors 8: Empires,0.04,0.02,0.06,0.571429
2139,NBA 2K16,0.77,0.10,0.87,0.793814
8310,Cabela's Legendary Adventures,0.16,0.00,0.16,0.941176

In [31]:
nombres   = df_limpio["Name"]          # Series
regiones  = df_limpio[["Name", "ventas_na", "ventas_eu"]]  # DataFrame
print(type(nombres), type(regiones))

<class 'pandas.core.series.Series'> <class 'pandas.core.frame.DataFrame'>

In [32]:
nintendo = df_limpio[df_limpio["Publisher"] == "Nintendo"]
print(f"Juegos de Nintendo: {len(nintendo)}")
nintendo[["Name", "Genre", "ventas_global"]].head(8)

Juegos de Nintendo: 696

                       Name         Genre  ventas_global
0                Wii Sports        Sports          82.74
1         Super Mario Bros.      Platform          40.24
2            Mario Kart Wii        Racing          35.82
3         Wii Sports Resort        Sports          33.00
4  Pokemon Red/Pokemon Blue  Role-Playing          31.37
5                    Tetris        Puzzle          30.26
6     New Super Mario Bros.      Platform          30.01
7                  Wii Play          Misc          29.02

In [33]:
nintendoShooter = df_limpio[
    (df_limpio["Publisher"] == "Nintendo") &
    (df_limpio["Genre"] == "Shooter")
]
print(nintendoShooter[["Name", "Platform", "ventas_global"]])

                                     Name Platform  ventas_global
9                               Duck Hunt      NES          28.31
84                          GoldenEye 007      N64           8.09
206              Link's Crossbow Training      Wii           5.00
235                              Splatoon     WiiU           4.57
296                           Star Fox 64      N64           4.03
472                              Star Fox     SNES           2.99
519                         Metroid Prime       GC           2.82
955           Metroid Prime 3: Corruption      Wii           1.82
1108                        Super Scope 6     SNES           1.65
1476              Metroid Prime 2: Echoes       GC           1.33
1560                        Hogan's Alley      NES           1.27
1678                         SolarStriker       GB           1.20
1750                     Jet Force Gemini      N64           1.16
1914                    Star Fox: Assault       GC           1.08
2197                       Star Fox 64 3D      3DS           0.94
2632                Metroid Prime Hunters       DS           0.78
3214               Metroid Prime: Trilogy      Wii           0.63
3740                     Star Fox Command       DS           0.54
4453   Sin and Punishment: Star Successor      Wii           0.44
5288                       Star Fox: Zero     WiiU           0.35
6767          Classic NES Series: Xevious      GBA           0.25
7094                         Super R-Type     SNES           0.23
9479                   Sin and Punishment      N64           0.13
11514          Famicom Mini: Star Soldier      GBA           0.08

In [34]:
# Funciones de agregación + groupby

ventas_por_genero = (
    df_limpio
    .groupby("Genre")["ventas_global"]
    .agg(["sum", "mean", "count"])
    .rename(columns={"sum": "total_M", "mean": "proemdio_M", "count": "n_juegos"})
    .sort_values("total_M", ascending=False)
)

ventas_por_genero

              total_M  proemdio_M  n_juegos
Genre
Action        1722.84    0.529942      3251
Sports        1309.24    0.568247      2304
Shooter       1026.20    0.800468      1282
Role-Playing   923.83    0.628456      1470
Platform       829.13    0.947577       875
Misc           789.87    0.468488      1686
Racing         726.76    0.593273      1225
Fighting       444.05    0.531160       836
Simulation     389.98    0.459882       848
Puzzle         242.21    0.424930       570
Adventure      234.59    0.184137      1274
Strategy       173.27    0.258612       670

In [37]:
# Tabla pivote

top_generos = ["Action", "Sports", "Shooter", "Role-Playing", "Racing"]
top_plataformas = ["PS2", "X360", "Wii", "PS3", "DS"]

pivot = pd.pivot_table(
    df_limpio[df_limpio["Genre"].isin(top_generos) &
              df_limpio["Platform"].isin(top_plataformas)],
    values= "ventas_global",
    index = "Genre",
    columns="Platform",
    aggfunc="sum",
    fill_value=0
)
pivot

Platform          DS     PS2     PS3     Wii    X360
Genre
Action        114.16  272.43  304.02  110.48  239.67
Racing         38.58  154.21   73.10   61.24   65.13
Role-Playing  126.56   91.55   75.24   14.06   71.97
Shooter         8.20  108.28  195.80   26.34  277.23
Sports         31.71  262.64  134.91  289.95  137.43

In [38]:
# Distrubución de valores

print(df_limpio["Genre"].value_counts())

Genre
Action          3251
Sports          2304
Misc            1686
Role-Playing    1470
Shooter         1282
Adventure       1274
Racing          1225
Platform         875
Simulation       848
Fighting         836
Strategy         670
Puzzle           570
Name: count, dtype: int64

# Matplotlib